### PR TITLE
Get v4 to work

### PR DESCRIPTION
**Pull request by michielbdejong**

### CODE REVIEW

**Comment by michielbdejong** [comment]
This is what worked on my server; will recreate it from scratch to double-check that it still works then.

**Comment by michielbdejong** [comment]
Goes together with https://github.com/interledgerjs/ilp-kit/pull/479

**Comment by dappelt** [comment]
Can I test this somehow on localhost?

**Comment by michielbdejong** [comment]
No, you can only test it on a publically addressable server.

**Comment by dappelt** [comment]
Installation worked and the login page shows up, but login does not work.

https://hive.dennisappelt.com

**Comment by michielbdejong** [comment]
You should check out the mj-docker-fixes2 branch of ilp-kit on the server and then run: 
```sh
docker build .
docker tag asdfasdf interledgerjs/ilp-kit #asdfasdf is the image that was built
cd ../ilp-kit-docker-compose
ILP_DOMAIN='ilp-kit.michielbdejong.com' \
	ILP_EMAIL='michiel@unhosted.org' \
	ILP_CURRENCY='USD' \
	ILP_SECRET='wawawa' \
	NODE_ENV='production' \
docker-compose up -d

**Comment by michielbdejong** [comment]
Try it on https://ilp-kit.michielbdejong.com/ with alice / alice

**Comment by michielbdejong** [comment]
Tested this with a fresh server (Ubuntu 17.04, 2048Mb memory, 10 USD/month at vultr.com):

```sh
apt-get update
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update
apt-get install docker-ce
curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
git clone https://github.com/interledgerjs/ilp-kit
cd ilp-kit/
git checkout mj-docker-fixes2
docker build -t interledgerjs/ilp-kit .
cd ..
git clone https://github.com/interledgerjs/ilp-kit-docker-compose
cd ilp-kit-docker-compose/
git checkout mj-docker-fixes2
vim up.sh
sh up.sh
```
up.sh contains:
```sh
ILP_DOMAIN='ilp-kit2.michielbdejong.com' \
ILP_EMAIL='michiel@unhosted.org' \
ILP_CURRENCY='USD' \
ILP_SECRET='**********' \
AMUNDSEN_USERNAME='baikahphuuToo1eiju4e' \
AMUNDSEN_PASSWORD='************' \
NODE_ENV='production' \
docker-compose up -d
```

**Pull request merged**
